---
- name: MariaDB
  hosts: all
  gather_facts: true
  become: true
  vars:
    mysql_root_password: "Password1"
  tasks:
    - name: install mariadb
      yum:
        name:
          - mariadb-server
          - python3-PyMySQL
          - MySQL-python
        state: latest
    - name: start mariadb
      service:
        name: mariadb
        enabled: true
        state: started
    - name: mysql_root_password
      mysql_user:
        login_user: root
        login_password: "{{ mysql_root_password }}"
        user: root
        check_implicit_admin: true
    - name: Create .my.cnf
      template:
         src: "client.my.cnf.j2"
         dest: "/root/.my.cnf"
         owner: root
         group: root
         mode: 0600

    - name: create database nova
      mysql_db:
        name: nova
        state: present
